/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.9/userguide/multi_project_builds.html
 */

rootProject.name = "gradle-effective-impl"

include(
  "ch01-01",
  "ch02-01",
  "ch02-02",
  "ch02-03",
  "ch02-04",
  "ch02-05"
)
